global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # random rules you may want prometheus to load

scrape_configs:
  #configures prometheus to monitor itself :)
  - job_name: prometheus
    static_configs:
      - targets: ['18.209.167.158:9090']
  
  - job_name: EC2Node
    static_configs:
      - targets: ['18.209.167.158:9100']

  - job_name: mysql
    static_configs:
      - targets: ['18.209.167.158:9100']
     
 